---
schema: olm.package
name: cywell-opsmate
defaultChannel: alpha
---
schema: olm.channel
package: cywell-opsmate
name: alpha
entries:
- name: cywell-opsmate.v0.0.52
  replaces: cywell-opsmate.v0.0.51
- name: cywell-opsmate.v0.0.51
  replaces: cywell-opsmate.v0.0.50
- name: cywell-opsmate.v0.0.50
  replaces: cywell-opsmate.v0.0.49
- name: cywell-opsmate.v0.0.49
  replaces: cywell-opsmate.v0.0.48
- name: cywell-opsmate.v0.0.48
  replaces: cywell-opsmate.v0.0.47
- name: cywell-opsmate.v0.0.47
  replaces: cywell-opsmate.v0.0.46
- name: cywell-opsmate.v0.0.46
  replaces: cywell-opsmate.v0.0.45
- name: cywell-opsmate.v0.0.45
  replaces: cywell-opsmate.v0.0.44
- name: cywell-opsmate.v0.0.44
  replaces: cywell-opsmate.v0.0.43
- name: cywell-opsmate.v0.0.43
  replaces: cywell-opsmate.v0.0.42
- name: cywell-opsmate.v0.0.42
  replaces: cywell-opsmate.v0.0.41
- name: cywell-opsmate.v0.0.41
  replaces: cywell-opsmate.v0.0.40
- name: cywell-opsmate.v0.0.40
  replaces: cywell-opsmate.v0.0.39
- name: cywell-opsmate.v0.0.39
  replaces: cywell-opsmate.v0.0.38
- name: cywell-opsmate.v0.0.38
  replaces: cywell-opsmate.v0.0.37
- name: cywell-opsmate.v0.0.37
  replaces: cywell-opsmate.v0.0.34
- name: cywell-opsmate.v0.0.34
  replaces: cywell-opsmate.v0.0.33
- name: cywell-opsmate.v0.0.33
  replaces: cywell-opsmate.v0.0.32
- name: cywell-opsmate.v0.0.32
  replaces: cywell-opsmate.v0.0.31
- name: cywell-opsmate.v0.0.31
  replaces: cywell-opsmate.v0.0.29
- name: cywell-opsmate.v0.0.29
---
schema: olm.bundle
name: cywell-opsmate.v0.0.52
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.52
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.52
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.52
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.52
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.51
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.51
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.51
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.51
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.51
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.50
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.50
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.50
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.50
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.50
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.49
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.49
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.49
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.49
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.49
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.48
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.48
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.48
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.48
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.48
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.47
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.47
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.47
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.47
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.47
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.46
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.46
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.46
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.46
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.46
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.45
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.45
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.45
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.45
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.45
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.44
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.44
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.44
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.44
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.44
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.43
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.43
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.43
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.43
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.43
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.42
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.42
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.42
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.42
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.42
- name: gateway
  image: nginxinc/nginx-unprivileged:1.27-alpine
---
schema: olm.bundle
name: cywell-opsmate.v0.0.41
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.41
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.41
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.41
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.41
---
schema: olm.bundle
name: cywell-opsmate.v0.0.40
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.40
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.40
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.40
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.40
---
schema: olm.bundle
name: cywell-opsmate.v0.0.39
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.39
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.39
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.39
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.39
---
schema: olm.bundle
name: cywell-opsmate.v0.0.38
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.38
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.38
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.38
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.38
---
schema: olm.bundle
name: cywell-opsmate.v0.0.37
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.37
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.37
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.37
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.37
---
schema: olm.bundle
name: cywell-opsmate.v0.0.34
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.34
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.34
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.34
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.27
---
schema: olm.bundle
name: cywell-opsmate.v0.0.33
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.33
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.33
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.33
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.27
---
schema: olm.bundle
name: cywell-opsmate.v0.0.32
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.32
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.32
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.32
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.27
---
schema: olm.bundle
name: cywell-opsmate.v0.0.31
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.31
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.31
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.31
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.27
---
schema: olm.bundle
name: cywell-opsmate.v0.0.29
package: cywell-opsmate
image: ghcr.io/jungyuoo/cywell-opsmate-bundle:v0.0.29
properties:
- type: olm.gvk
  value:
    group: opsmate.cywell.io
    kind: OpsMateConfig
    version: v1alpha1
- type: olm.package
  value:
    packageName: cywell-opsmate
    version: 0.0.29
relatedImages:
- name: manager
  image: ghcr.io/jungyuoo/cywell-opsmate:v0.0.28
- name: appserver
  image: ghcr.io/jungyuoo/cywell-opsmate-appserver:v0.0.27
